services:
  house_workflow:
    container_name: house_workflow
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    ports:
      - 1335:80
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/default-host.conf:/etc/nginx/sites-available/default-host.conf
      - ./docker/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-override.conf
    environment:
      - APP_HOME=/var/www/app
      - HOST_UID=1000
      - HOST_GID=1000
      - USERNAME=www-data
      - DEBIAN_FRONTEND=noninteractive
      - DEBCONF_NOWARNINGS=yes

  house_workflow_db:
    container_name: house_workflow_db
    image: postgres:16
    environment:
      POSTGRES_DB: house_workflow
      POSTGRES_USER: house_workflow
      POSTGRES_PASSWORD: ChangeMe12345
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
